
#cursor
exec-once = hyprctl setcursor Bibata-Modern-Ice 24

#network manager
exec-once = nm-applet

#OSD notifications for volume up and down
exec-once = swayosd-server

# Aplication launcher
exec-once = albert

# Using hypridle to start hyprlock
exec-once = hypridle

# Load cliphist history
exec-once = wl-paste --watch cliphist store

