# Pavucontrol floating
windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = size 700 600, match:class org.pulseaudio.pavucontrol
windowrule = center on, match:class org.pulseaudio.pavucontrol
windowrule = pin on, match:class org.pulseaudio.pavucontrol

# Gnome Calculator
windowrule = float yes,match:class org.gnome.Calculator
windowrule = size 700 600, match:class org.gnome.Calculator
windowrule = center on, match:class org.gnome.Calculator

# blueman-manager
windowrule = float on, match:class blueman-manager
windowrule = center on, match:class blueman-manager
windowrule = pin on, match:class blueman-manager
windowrule = size 700 600, match:class blueman-manager

# General floating
windowrule = float on, match:class (dotfiles.floating)
windowrule = size 1000 750, match:class (dotfiles.floating)
windowrule = center match:class (dotfiles.floating)
windowrule = pin on, match:class (dotfiles.floating)

